name: seastates
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip
  - pip:
    - cmocean==4.0.3
    - IPython==9.6.0
    - matplotlib==3.10.7
    - mhkit==1.0.1
    - netCDF4==1.7.2
    - numpy>=2.0.0
    - pandas==2.3.3
    - pymannkendall==1.4.3
    - pyextremes==2.3.3
    - pyproj==3.7.2
    - resourcecode==1.3.1
    - scipy==1.13.1
    - xarray==2024.6.0

